namespace Lyt.QrCode.API;

// See:  https://en.wikipedia.org/wiki/QR_code 

// Present in GlobalUsings.cs: BUT KEEP for avoiding ambiguous reference to System.Net
using Lyt.QrCode.Content;

/// <summary> 
/// Callback which is invoked when a possible significant point in the QR code image, such as a corner, is found.
/// </summary>
public delegate void DetectorCallback(ResultPoint point);

/// Factory class for creating QR code images and vector paths from various content types.
public static partial class Qr
{
    #region This region might be useless now....
    
    ///  should be autogenerated - Investigate source generators for this purpose

    //public static bool TryEncodeToImage(
    //    string content,
    //    [NotNullWhen(true)] out byte[]? image,
    //    RenderParameters? renderParameters = null)
    //    => Qr.TryEncode<string, byte[]>(content, out image, renderParameters);

    //public static string EncodeToVectors(string content, RenderParameters? renderParameters = default)
    //    => Qr.EncodeToVectors(new StringContent(content), renderParameters);

    //public static bool[,] EncodeToModules(string content, RenderParameters? renderParameters = default)
    //    => Qr.EncodeToVectors(new StringContent(content), renderParameters);


    //public static byte[] EncodeToImage(byte[] content, RenderParameters? renderParameters = default)
    //    => Qr.EncodeToImage(new BytesContent(content), renderParameters);

    //public static string EncodeToVectors(byte[] content, RenderParameters? renderParameters = default)
    //    => Qr.EncodeToVectors(new BytesContent(content), renderParameters);

    //public static byte[] EncodeToImage(WebLink weblink, RenderParameters? renderParameters = default)
    //    => Qr.EncodeToImage(new WebLinkContent(weblink), renderParameters);

    //public static string EncodeToVectors(WebLink weblink, RenderParameters? renderParameters = default)
    //    => Qr.EncodeToVectors(new WebLinkContent(weblink), renderParameters);

    #endregion // This region should be autogenerated - Investigate source generators for this purpose

    public static bool TryEncode<TContent, TResult>(
        TContent content,
        [NotNullWhen(true)] out TResult? result,
        RenderParameters? renderParameters = null)
        where TContent : class
        where TResult : class
    {
        // message = string.Empty;
        result = null;
        renderParameters ??= new RenderParameters();
        if (!renderParameters.Validate())
        {
            // Invalid parameters - use default values
            if (Debugger.IsAttached) { Debugger.Break(); }
            renderParameters = new RenderParameters();
        }

        if (!TryCreateQrContent<TContent>(content, out QrContent? qrContent))
        {
            return false;
        }

        if (!TryDetermineDecoderOutput<TResult>(out EncoderOutput encoderOutput)
            || encoderOutput == EncoderOutput.Unsupported)
        {
            return false;
        }

        try
        {
            var qrCode =
                qrContent.IsBinaryData ?
                    QrCode.EncodeBytes(qrContent.RawBytes, ErrorCorrectionLevel.Quartile) :
                    QrCode.EncodeText(qrContent.RawString, ErrorCorrectionLevel.Quartile);

            object? rawResult; 
            switch (encoderOutput)
            {
                default:
                case EncoderOutput.Unsupported:
                    return false;

                case EncoderOutput.Image:
                    switch (renderParameters.ImageFormat)
                    {
                        default:
                            return false;

                        case RenderParameters.QrImageFormat.Png:
                            byte[] pngImage =
                                PngBuilder.ToPngImage(
                                    qrCode,
                                    renderParameters.Scale,
                                    renderParameters.Border,
                                    renderParameters.Foreground,
                                    renderParameters.Background);
                            rawResult = pngImage;
                            break;
                    }

                    break;

                case EncoderOutput.Vectors:
                    string vectorPath =
                        PathBuilder.ToSvgImageString(
                            qrCode,
                            renderParameters.Border,
                            renderParameters.Foreground,
                            renderParameters.Background,
                            renderParameters.VectorFormat);
                    rawResult = vectorPath;
                    break;

                case EncoderOutput.Modules:
                    bool[,] modules = qrCode.GetModules();
                    rawResult = modules;
                    break;
            }

            if (rawResult.GetType() == typeof(TResult))
            {
                // Safe to cast
                result = (TResult) rawResult;
                return true;
            } 
        }
        catch (Exception ex)
        {
            if (Debugger.IsAttached) { Debugger.Break(); }
            Debug.WriteLine(ex.ToString());
        }

        return false;
    }

    private static bool TryCreateQrContent<T>(
        T content, [NotNullWhen(true)] out QrContent? qrContent)
        where T : class
    {
        qrContent = null;
        if (content is null)
        {
            return false;
        }

        if (content is string stringContent)
        {
            qrContent = new StringContent(stringContent);
            return true;
        }

        if (content is byte[] bytesContent)
        {
            qrContent = new BytesContent(bytesContent);
            return true;
        }

        if (content is WebLink linkContent)
        {
            qrContent = new WebLinkContent(linkContent);
            return true;
        }

        // Unsupported content type
        return false;
    }

    private static bool TryDetermineDecoderOutput<T>(out EncoderOutput encoderOutput) where T : class
    {
        encoderOutput = EncoderOutput.Unsupported;
        if (typeof(T) == typeof(byte[]))
        {
            encoderOutput = EncoderOutput.Image;
        }
        else if (typeof(T) == typeof(string))
        {
            encoderOutput = EncoderOutput.Vectors;
        } 
        else if (typeof(T) == typeof(bool[,]))
        {
            encoderOutput = EncoderOutput.Modules;
        }

        return false ; 
    }


    public static bool TryDecodeQrCodeFromImage(
        SourceImage sourceImage,
        [NotNullWhen(true)] out DecoderResult? decoderResult,
        DetectorCallback? detectorCallback = null,
        DecodeParameters? decodeParameters = null)
    {
        decoderResult = null;
        decodeParameters ??= new DecodeParameters();
        if (!decodeParameters.Validate())
        {
            // Invalid parameters - use default values
            if (Debugger.IsAttached) { Debugger.Break(); }
            decodeParameters = new DecodeParameters();
        }

        if (sourceImage.TryDecode(decodeParameters, detectorCallback, out decoderResult))
        {
            return true;
        }

        return false;
    }
}
