namespace Lyt.QrCode.API;

// See:  https://en.wikipedia.org/wiki/QR_code 

// Present in GlobalUsings.cs: BUT KEEP for avoiding ambiguous reference to System.Net
using Lyt.QrCode.Content;

/// <summary> 
/// Callback which is invoked when a possible result point (significant
/// point in the QR code image such as a corner) is found.
/// </summary>
public delegate void DetectorCallback(ResultPoint point);

/// Factory class for creating QR code images and vector paths from various content types.
public static partial class QrFactory
{
    #region This region should be autogenerated - Investigate source generators for this purpose

    public static byte[] CreateQrCodeImage(string content, RenderParameters? renderParameters = null)
        => QrFactory.CreateQrCodeImage(new StringContent(content), renderParameters);

    public static string CreateQrCodeVectorPath(string content, RenderParameters? renderParameters = default)
        => QrFactory.CreateQrCodeVectorPath(new StringContent(content), renderParameters);

    public static byte[] CreateQrCodeImage(byte[] content, RenderParameters? renderParameters = default)
        => QrFactory.CreateQrCodeImage(new BytesContent(content), renderParameters);

    public static string CreateQrCodeVectorPath(byte[] content, RenderParameters? renderParameters = default)
        => QrFactory.CreateQrCodeVectorPath(new BytesContent(content), renderParameters);

    public static byte[] CreateQrCodeImage(WebLink weblink, RenderParameters? renderParameters = default)
        => QrFactory.CreateQrCodeImage(new WebLinkContent(weblink), renderParameters);

    public static string CreateQrCodeVectorPath(WebLink weblink, RenderParameters? renderParameters = default)
        => QrFactory.CreateQrCodeVectorPath(new WebLinkContent(weblink), renderParameters);

    #endregion // This region should be autogenerated - Investigate source generators for this purpose

    public static byte[] CreateQrCodeImage<T>(
        QrContent<T> content,
        RenderParameters? renderParameters = null)
        where T : class
    {
        var qrCode =
            content.IsBinaryData ?
                QrCode.EncodeBytes(content.RawBytes, Ecc.Quartile) :
                QrCode.EncodeText(content.RawString, Ecc.Quartile);
        renderParameters ??= new RenderParameters();
        if (!renderParameters.Validate())
        {
            // Invalid parameters - use default values
            if ( Debugger.IsAttached) { Debugger.Break(); }
            renderParameters = new RenderParameters();
        }

        byte[] pngImage =
            PngBuilder.ToPngImage(
                qrCode,
                renderParameters.Scale,
                renderParameters.Border,
                renderParameters.Foreground,
                renderParameters.Background);
        return pngImage;
    }

    public static string CreateQrCodeVectorPath<T>(
        QrContent<T> content,
        RenderParameters? renderParameters = null)
        where T : class
    {
        var qrCode =
            content.IsBinaryData ?
                QrCode.EncodeBytes(content.RawBytes, Ecc.Quartile) :
                QrCode.EncodeText(content.RawString, Ecc.Quartile);
        renderParameters ??= new RenderParameters();
        if (!renderParameters.Validate())
        {
            // Invalid parameters - use default values
            if (Debugger.IsAttached) { Debugger.Break(); }
            renderParameters = new RenderParameters();
        }

        string vectorPath =
            PathBuilder.ToSvgImageString(
                qrCode,
                renderParameters.Border,
                renderParameters.Foreground,
                renderParameters.Background, 
                renderParameters.VectorFormat);
        return vectorPath;
    }

    public static bool DecodeQrCodeFromImage(
        SourceImage sourceImage,
        [NotNullWhen(true)] out DecoderResult? decoderResult,
        DetectorCallback? detectorCallback = null,
        DecodeParameters? decodeParameters = null)
    {
        decoderResult = null;
        decodeParameters ??= new DecodeParameters();
        if (!decodeParameters.Validate())
        {
            // Invalid parameters - use default values
            if (Debugger.IsAttached) { Debugger.Break(); }
            decodeParameters = new DecodeParameters();
        }

        if (sourceImage.TryDecode(decodeParameters, detectorCallback, out decoderResult))
        {
            return true;
        }

        return false;
    }
}
